### ISSUE TITLE
Editor not opening because it "could not load the required fallback font"

### ISSUE THREAD

**Issue by NicknEma** [4coder-community/4cc#8]
I have just downloaded and built the community fork and it won't open, showing the error message above. The executable is in `C:\dev\4coder\build`.

I stepped through the code in Visual Studio and it appears that in `4ed.cpp` line 266, `push_u8_stringf` is returning a bogus path (non printable characters and a length of 2 billions or something). I didn't investigate further.

**Comment by zhedye** [comment]
I ran into the same issue. It is looking for a font with file_name `build\fonts/liberation-mono.ttf`.

If you run 4ed.exe from `current_dist_super_x64\4coder` it will work because the fonts folder has been copied there. You can also copy the fonts folder into the build directory and it will work.

The README doesn't explain this.

**Comment by Jack-Punter** [comment]
This is the difference between the `build.sh/bat` and `package.sh/bat` scripts mentioned in the README , the build system is pretty confusing, but I've updated the README here (#13) to explain this a little better.
